// packages/react/src/Accordion.tsx
// @ts-nocheck
import React, { useState } from "react";

/**
 * Accordion
 * React wrapper for Mayvio UI Accordion component.
 *
 * Props:
 * - multiExpand: whether multiple panels can be expanded at once
 * - children: AccordionItem components
 * - className: custom class names
 */
export function Accordion({ children, multiExpand = false, className = "" }) {
  const [openIndices, setOpenIndices] = useState([]);

  const handleToggle = (index) => {
    if (multiExpand) {
      if (openIndices.includes(index)) {
        setOpenIndices(openIndices.filter((i) => i !== index));
      } else {
        setOpenIndices([...openIndices, index]);
      }
    } else {
      setOpenIndices(openIndices.includes(index) ? [] : [index]);
    }
  };

  return (
    <div className={`accordion ${className}`}>
      {React.Children.map(children, (child, index) => {
        if (!React.isValidElement(child)) return null;
        return React.cloneElement(child, {
          isOpen: openIndices.includes(index),
          onToggle: () => handleToggle(index)
        });
      })}
    </div>
  );
}

/**
 * AccordionItem
 * Individual collapsible item inside Accordion.
 */
export function AccordionItem({ title, isOpen = false, onToggle, children, className = "" }) {
  return (
    <div className={`accordion-item ${isOpen ? "open" : ""} ${className}`}>
      <button
        className="accordion-trigger"
        aria-expanded={isOpen}
        onClick={onToggle}
        type="button"
      >
        {title}
        <span className="accordion-icon" aria-hidden="true">▼</span>
      </button>
      <div className="accordion-content">
        <div className="accordion-content-inner">
          <div className="accordion-body">{children}</div>
        </div>
      </div>
    </div>
  );
}

// packages/angular/src/accordion.component.ts
// @ts-nocheck
import { Component, Input, ContentChildren, QueryList, AfterContentInit } from "@angular/core";

/**
 * AccordionItemComponent
 * Individual accordion panels holding header details and projected bodies.
 */
@Component({
  selector: "mayvio-accordion-item",
  template: `
    <div class="accordion-item" [class.open]="isOpen">
      <button class="accordion-trigger" [attr.aria-expanded]="isOpen" (click)="toggle()" type="button">
        {{ title }}
        <span class="accordion-icon" aria-hidden="true">▼</span>
      </button>
      <div class="accordion-content">
        <div class="accordion-content-inner">
          <div class="accordion-body">
            <ng-content></ng-content>
          </div>
        </div>
      </div>
    </div>
  `
})
export class AccordionItemComponent {
  @Input() title = "";
  @Input() isOpen = false;

  toggle() {
    this.isOpen = !this.isOpen;
  }
}

/**
 * AccordionComponent
 * Container organizing multiple AccordionItem components.
 */
@Component({
  selector: "mayvio-accordion",
  template: `
    <div class="accordion">
      <ng-content></ng-content>
    </div>
  `
})
export class AccordionComponent implements AfterContentInit {
  @Input() multiExpand = false;
  @ContentChildren(AccordionItemComponent) items!: QueryList<AccordionItemComponent>;

  ngAfterContentInit() {
    this.items.forEach((item) => {
      const originalToggle = item.toggle.bind(item);
      item.toggle = () => {
        const nextState = !item.isOpen;
        if (!this.multiExpand && nextState) {
          this.items.forEach((other) => {
            if (other !== item) other.isOpen = false;
          });
        }
        item.isOpen = nextState;
      };
    });
  }
}
