// packages/react/src/Badge.tsx
// @ts-nocheck
import React from "react";

/**
 * Badge
 * React wrapper for Mayvio UI Badge component.
 *
 * Props:
 * - variant: 'success' | 'error' | 'warning' | 'info'
 * - dot: whether to show a status dot
 * - outline: whether to show the outline variant
 * - children: text content
 * - className: custom class names
 */
export function Badge({ variant = "info", dot = false, outline = false, children, className = "" }) {
  const classes = [
    "badge",
    variant,
    dot ? "dot" : "",
    outline ? "outline" : "",
    className
  ]
    .filter(Boolean)
    .join(" ");

  return <span className={classes}>{children}</span>;
}

// packages/angular/src/badge.component.ts
// @ts-nocheck
import { Component, Input } from "@angular/core";

/**
 * BadgeComponent
 * Angular wrapper component for Mayvio UI Badges.
 */
@Component({
  selector: "mayvio-badge",
  template: `
    <span [ngClass]="classes">
      <ng-content></ng-content>
    </span>
  `
})
export class BadgeComponent {
  @Input() variant: "success" | "error" | "warning" | "info" = "info";
  @Input() dot = false;
  @Input() outline = false;

  get classes() {
    return {
      "badge": true,
      "success": this.variant === "success",
      "error": this.variant === "error",
      "warning": this.variant === "warning",
      "info": this.variant === "info",
      "dot": this.dot,
      "outline": this.outline
    };
  }
}
