// packages/react/src/Breadcrumb.tsx
// @ts-nocheck
import React from "react";

/**
 * Breadcrumb
 * React wrapper for Mayvio UI Breadcrumb component.
 *
 * Props:
 * - items: array of { label: string, href?: string, active?: boolean, onClick?: function }
 * - className: custom class names
 */
export function Breadcrumb({ items = [], className = "" }) {
  return (
    <nav className={`breadcrumb ${className}`} aria-label="Breadcrumb">
      {items.map((item, index) => {
        const isLast = index === items.length - 1;
        const isCurrent = item.active !== undefined ? item.active : isLast;

        return (
          <React.Fragment key={item.label}>
            {index > 0 && (
              <span className="breadcrumb-separator" aria-hidden="true">/</span>
            )}
            {isCurrent ? (
              <span aria-current="page">{item.label}</span>
            ) : (
              <a href={item.href || "#"} onClick={item.onClick}>
                {item.label}
              </a>
            )}
          </React.Fragment>
        );
      })}
    </nav>
  );
}

// packages/angular/src/breadcrumb.component.ts
// @ts-nocheck
import { Component, Input, Output, EventEmitter } from "@angular/core";

export interface BreadcrumbItem {
  label: string;
  href?: string;
  active?: boolean;
}

/**
 * BreadcrumbComponent
 * Angular wrapper component representing the navigation breadcrumb trail.
 */
@Component({
  selector: "mayvio-breadcrumb",
  template: `
    <nav class="breadcrumb" aria-label="Breadcrumb">
      <ng-container
        *ngFor="let item of items; let idx = index; let isLast = last"
      >
        <span *ngIf="idx > 0" class="breadcrumb-separator" aria-hidden="true"
          >/</span
        >

        <span
          *ngIf="item.active || (item.active === undefined && isLast)"
          aria-current="page"
        >
          {{ item.label }}
        </span>

        <a
          *ngIf="!item.active && !(item.active === undefined && isLast)"
          [href]="item.href || '#'"
          (click)="onItemClick($event, item)"
        >
          {{ item.label }}
        </a>
      </ng-container>
    </nav>
  `
})
export class BreadcrumbComponent {
  @Input() items: BreadcrumbItem[] = [];
  @Output() navigate = new EventEmitter<BreadcrumbItem>();

  onItemClick(event: MouseEvent, item: BreadcrumbItem) {
    if (item.href === undefined || item.href === "#") {
      event.preventDefault();
    }
    this.navigate.emit(item);
  }
}
