// packages/react/src/Skeleton.tsx
// @ts-nocheck
import React from "react";

/**
 * Skeleton
 * React wrapper for Mayvio UI Skeleton Loader component.
 *
 * Props:
 * - variant: 'line' | 'avatar' | 'block' | 'rect'
 * - animation: 'shimmer' | 'wave' | 'pulse'
 * - width: CSS width value (e.g. '100%', '40px')
 * - height: CSS height value
 * - className: custom class names
 * - style: custom style object
 */
export function Skeleton({
  variant = "line",
  animation = "shimmer",
  width,
  height,
  className = "",
  style = {}
}) {
  const classes = [
    "skeleton",
    variant === "avatar" ? "avatar" : "",
    variant === "line" ? "line" : "",
    (variant === "block" || variant === "rect") ? "block" : "",
    animation,
    className
  ]
    .filter(Boolean)
    .join(" ");

  const combinedStyle = {
    ...(width ? { width } : {}),
    ...(height ? { height } : {}),
    ...style
  };

  return <div className={classes} style={combinedStyle} />;
}

// packages/angular/src/skeleton.component.ts
// @ts-nocheck
import { Component, Input } from "@angular/core";

/**
 * SkeletonComponent
 * Angular wrapper component for the Mayvio UI Skeleton Loader.
 */
@Component({
  selector: "mayvio-skeleton",
  template: `
    <div [ngClass]="classes" [ngStyle]="styles"></div>
  `
})
export class SkeletonComponent {
  @Input() variant: "line" | "avatar" | "block" | "rect" = "line";
  @Input() animation: "shimmer" | "wave" | "pulse" = "shimmer";
  @Input() width?: string;
  @Input() height?: string;

  get classes() {
    return {
      "skeleton": true,
      "avatar": this.variant === "avatar",
      "line": this.variant === "line",
      "block": this.variant === "block" || this.variant === "rect",
      "shimmer": this.animation === "shimmer",
      "wave": this.animation === "wave",
      "pulse": this.animation === "pulse"
    };
  }

  get styles() {
    return {
      ...(this.width ? { width: this.width } : {}),
      ...(this.height ? { height: this.height } : {})
    };
  }
}
