// packages/angular/src/avatar.component.ts
// @ts-nocheck
import { Component, Input, ContentChildren, QueryList, AfterContentInit } from "@angular/core";

/**
 * AvatarComponent
 * Angular wrapper component representing image or initials avatars.
 */
@Component({
  selector: "mayvio-avatar",
  template: `
    <span *ngIf="!hidden" class="avatar {{ size }}">
      <img *ngIf=" src" [src]="src" [attr.alt]="alt" />
      <ng-container *ngIf="!src">{{ initials }}</ng-container>
    </span>
  `
})
export class AvatarComponent {
  @Input() src = "";
  @Input() alt = "";
  @Input() initials = "";
  @Input() size: "sm" | "md" | "lg" = "md";
  hidden = false;
}

/**
 * AvatarGroupComponent
 * Groups and overlays multiple AvatarComponents with limit rules.
 */
@Component({
  selector: "mayvio-avatar-group",
  template: `
    <div class="avatar-group">
      <ng-content></ng-content>
      <span *ngIf="extraCount > 0" class="avatar sm more">+{{ extraCount }}</span>
    </div>
  `
})
export class AvatarGroupComponent implements AfterContentInit {
  @Input() limit?: number;
  @ContentChildren(AvatarComponent) avatars!: QueryList<AvatarComponent>;
  extraCount = 0;

  ngAfterContentInit() {
    if (this.limit && this.avatars.length > this.limit) {
      this.extraCount = this.avatars.length - this.limit;
      this.avatars.toArray().forEach((avatar, idx) => {
        if (idx >= this.limit) {
          avatar.hidden = true;
        }
      });
    }
  }
}

// packages/react/src/Avatar.tsx
// @ts-nocheck
import React from "react";

/**
 * Avatar
 * React wrapper for Mayvio UI Avatar component.
 *
 * Props:
 * - src: image URL
 * - alt: image alternate text
 * - initials: initials to display if image is missing
 * - size: 'sm' | 'md' | 'lg'
 * - className: custom class names
 */
export function Avatar({ src, alt = "", initials, size = "md", className = "" }) {
  const classes = ["avatar", size, className].filter(Boolean).join(" ");

  return (
    <span className={classes}>
      {src ? <img src={src} alt={alt} /> : initials}
    </span>
  );
}

/**
 * AvatarGroup
 * Stacks multiple Avatar components together with a limit fallback.
 */
export function AvatarGroup({ limit, children, className = "" }) {
  const childrenArray = React.Children.toArray(children);
  const visibleAvatars = limit ? childrenArray.slice(0, limit) : childrenArray;
  const extraCount = limit && childrenArray.length > limit ? childrenArray.length - limit : 0;

  return (
    <div className={`avatar-group ${className}`}>
      {visibleAvatars}
      {extraCount > 0 && <span className="avatar sm more">+{extraCount}</span>}
    </div>
  );
}
