// packages/angular/src/notification-center.component.ts
// @ts-nocheck
import { Component, Input, Output, EventEmitter, ContentChildren, QueryList } from "@angular/core";

/**
 * NotificationItemComponent
 * Angular wrapper component representing single notification alerts.
 */
@Component({
  selector: "mayvio-notification-item",
  template: `
    <div class="notification-item notification-item-{{ type }}">
      <div class="notification-badge" aria-hidden="true"></div>
      <div class="notification-info">
        <h4>{{ title }}</h4>
        <p *ngIf="description">{{ description }}</p>
      </div>
      <button
        class="notification-dismiss"
        aria-label="Dismiss notification"
        (click)="dismiss.emit()"
      >
        ✕
      </button>
    </div>
  `
})
export class NotificationItemComponent {
  @Input() type: "success" | "error" | "warning" | "info" = "info";
  @Input() title = "";
  @Input() description = "";
  @Output() dismiss = new EventEmitter<void>();
}

/**
 * NotificationCenterComponent
 * Angular wrapper component orchestrating the notification overlay lists.
 */
@Component({
  selector: "mayvio-notification-center",
  template: `
    <div class="notification-center-card">
      <button
        class="control-btn"
        (click)="toggle.emit()"
        [attr.aria-expanded]="isOpen"
        data-toggle-notifications
        type="button"
      >
        {{ isOpen ? "Hide notifications" : "Show notifications" }}
      </button>

      <div class="notification-panel" [class.is-open]="isOpen">
        <ng-content></ng-content>

        <div *ngIf="hasItems" class="notification-footer">
          <button data-clear-notifications (click)="clearAll.emit()">
            Clear all
          </button>
        </div>
      </div>
    </div>
  `
})
export class NotificationCenterComponent {
  @Input() isOpen = false;
  @Output() toggle = new EventEmitter<void>();
  @Output() clearAll = new EventEmitter<void>();

  @ContentChildren(NotificationItemComponent)
  items!: QueryList<NotificationItemComponent>;

  get hasItems() {
    return this.items && this.items.length > 0;
  }
}

// packages/react/src/NotificationCenter.tsx
// @ts-nocheck
import React from "react";

/**
 * NotificationCenter
 * React wrapper for Mayvio UI Notification Center component.
 *
 * Props:
 * - isOpen: boolean representing panel visibility
 * - onToggle: callback to open/close panel
 * - onClearAll: callback to clear notifications
 * - children: NotificationItem components
 * - className: custom class names
 */
export function NotificationCenter({
  isOpen = false,
  onToggle,
  onClearAll,
  children,
  className = ""
}) {
  const childrenArray = React.Children.toArray(children);

  return (
    <div className={`notification-center-card ${className}`}>
      {onToggle && (
        <button
          className="control-btn"
          onClick={onToggle}
          aria-expanded={isOpen}
          data-toggle-notifications
          type="button"
        >
          {isOpen ? "Hide notifications" : "Show notifications"}
        </button>
      )}

      <div className={`notification-panel ${isOpen ? "is-open" : ""}`}>
        {children}
        {childrenArray.length > 0 && onClearAll && (
          <div className="notification-footer">
            <button data-clear-notifications onClick={onClearAll} type="button">
              Clear all
            </button>
          </div>
        )}
        {childrenArray.length === 0 && (
          <div style={{ padding: "20px", textAlign: "center", color: "var(--text-muted)", fontSize: "0.85rem" }}>
            No notifications
          </div>
        )}
      </div>
    </div>
  );
}

/**
 * NotificationItem
 * Single notification card template.
 */
export function NotificationItem({
  type = "info",
  title,
  description,
  onDismiss,
  className = ""
}) {
  return (
    <div className={`notification-item notification-item-${type} ${className}`}>
      <div className="notification-badge" aria-hidden="true" />
      <div className="notification-info">
        <h4>{title}</h4>
        {description && <p>{description}</p>}
      </div>
      {onDismiss && (
        <button
          className="notification-dismiss"
          aria-label="Dismiss notification"
          onClick={onDismiss}
          type="button"
        >
          ✕
        </button>
      )}
    </div>
  );
}
