// packages/angular/src/progress-bar.component.ts
// @ts-nocheck
import { Component, Input, Output, EventEmitter } from "@angular/core";

/**
 * ProgressBarComponent
 * Angular wrapper component representing the Mayvio UI Progress Bar.
 */
@Component({
  selector: "mayvio-progress-bar",
  template: `
    <div class="progress-demo">
      <div class="progress-header">
        <span *ngIf="label" class="progress-label">{{ label }}</span>
        <span *ngIf="showValue" class="progress-value">
          {{ indeterminate ? "Loading…" : value + "%" }}
        </span>
      </div>

      <div class="progress-track" [class.indeterminate]="indeterminate">
        <div
          class="progress-fill"
          [style.width]="indeterminate ? null : value + '%'"
        ></div>
      </div>

      <input
        *ngIf="interactive && !indeterminate"
        type="range"
        class="progress-slider"
        min="0"
        max="100"
        [value]="value"
        (input)="onSliderChange($event)"
        [attr.aria-label]="label || 'Progress value'"
      />
    </div>
  `
})
export class ProgressBarComponent {
  @Input() value = 0;
  @Input() label = "";
  @Input() indeterminate = false;
  @Input() showValue = true;
  @Input() interactive = false;
  @Output() valueChange = new EventEmitter<number>();

  onSliderChange(event: Event) {
    const val = parseInt((event.target as HTMLInputElement).value, 10);
    this.value = val;
    this.valueChange.emit(val);
  }
}

// packages/react/src/ProgressBar.tsx
// @ts-nocheck
import React from "react";

/**
 * ProgressBar
 * React wrapper for Mayvio UI Progress Bar component.
 *
 * Props:
 * - value: number (0-100) representing current progress
 * - label: text descriptor
 * - indeterminate: whether the loading is indeterminate (animated loop)
 * - className: custom class names
 * - showValue: show percentage or text indicator
 * - onChange: optional function to render as an interactive range slider
 */
export function ProgressBar({
  value = 0,
  label = "",
  indeterminate = false,
  className = "",
  showValue = true,
  onChange
}) {
  const isInteractive = typeof onChange === "function";

  const handleSliderChange = (e) => {
    if (isInteractive) {
      onChange(parseInt(e.target.value, 10));
    }
  };

  return (
    <div className={`progress-demo ${className}`}>
      <div className="progress-header">
        {label && <span className="progress-label">{label}</span>}
        {showValue && (
          <span className="progress-value">
            {indeterminate ? "Loading…" : `${value}%`}
          </span>
        )}
      </div>

      <div className={`progress-track ${indeterminate ? "indeterminate" : ""}`}>
        <div
          className="progress-fill"
          style={{ width: indeterminate ? undefined : `${value}%` }}
        />
      </div>

      {isInteractive && !indeterminate && (
        <input
          type="range"
          className="progress-slider"
          min="0"
          max="100"
          value={value}
          onChange={handleSliderChange}
          aria-label={label || "Progress value"}
        />
      )}
    </div>
  );
}
