// packages/angular/src/sidebar.component.ts
// @ts-nocheck
import { Component, Input } from "@angular/core";

/**
 * SidebarLinkComponent
 * Angular wrapper component representing navigation links in the Sidebar menu.
 */
@Component({
  selector: "mayvio-sidebar-link",
  template: `
    <a
      [href]="href"
      class="sidebar-link"
      [class.active]="active"
      [attr.title]="label"
    >
      <span *ngIf="icon" class="sidebar-icon">{{ icon }}</span>
      <span class="sidebar-label">{{ label }}</span>
    </a>
  `
})
export class SidebarLinkComponent {
  @Input() active = false;
  @Input() icon = "";
  @Input() label = "";
  @Input() href = "#";
}

/**
 * SidebarComponent
 * Angular wrapper component representing the Navigation Sidebar panel.
 */
@Component({
  selector: "mayvio-sidebar",
  template: `
    <div class="sidebar" [class.is-collapsed]="collapsed">
      <nav class="sidebar-nav" aria-label="Sidebar menu">
        <ng-content></ng-content>
      </nav>
    </div>
  `
})
export class SidebarComponent {
  @Input() collapsed = false;
}

// packages/react/src/Sidebar.tsx
// @ts-nocheck
import React from "react";

/**
 * Sidebar
 * React wrapper for Mayvio UI Sidebar Navigation.
 *
 * Props:
 * - collapsed: boolean to collapse the sidebar width
 * - children: SidebarLink components
 * - className: custom class names
 */
export function Sidebar({ collapsed = false, children, className = "" }) {
  return (
    <div className={`sidebar ${collapsed ? "is-collapsed" : ""} ${className}`}>
      <nav className="sidebar-nav" aria-label="Sidebar menu">
        {children}
      </nav>
    </div>
  );
}

/**
 * SidebarLink
 * Anchor link items representing sidebar route items.
 */
export function SidebarLink({ active = false, icon, label, href = "#", onClick, className = "" }) {
  return (
    <a
      href={href}
      className={`sidebar-link ${active ? "active" : ""} ${className}`}
      onClick={onClick}
      title={label}
    >
      {icon && <span className="sidebar-icon">{icon}</span>}
      <span className="sidebar-label">{label}</span>
    </a>
  );
}
