// packages/angular/src/toast.component.ts
// @ts-nocheck
import { Component, Input, Output, EventEmitter } from "@angular/core";

/**
 * ToastComponent
 * Angular wrapper component representing static or inline toast designs.
 */
@Component({
  selector: "mayvio-toast",
  template: `
    <div class="toast {{ variant }}" role="alert">
      <span class="toast-icon" aria-hidden="true">{{ icon }}</span>
      <span class="toast-message">{{ message }}</span>
      <button
        *ngIf="dismissible"
        class="toast-close"
        aria-label="Dismiss notification"
        (click)="close.emit()"
      >
        ✕
      </button>
      <div class="toast-progress"></div>
    </div>
  `
})
export class ToastComponent {
  @Input() variant: "success" | "error" | "warning" | "info" = "info";
  @Input() message = "";
  @Input() dismissible = true;
  @Output() close = new EventEmitter<void>();

  get icon() {
    return {
      success: "✓",
      error: "✕",
      warning: "⚠",
      info: "ℹ"
    }[this.variant] || "ℹ";
  }
}

// packages/react/src/Toast.tsx
// @ts-nocheck
import React from "react";
import { createToast } from "mayvio-ui/scripts/components/toast.js";

// Re-export the programmatic toast creator
export { createToast as showToast };

/**
 * Toast
 * React wrapper for a static or inline Mayvio UI Toast Notification.
 *
 * Props:
 * - variant: 'success' | 'error' | 'warning' | 'info'
 * - message: text content of the toast
 * - dismissible: whether to show the close button
 * - onClose: callback event when close button is clicked
 */
export function Toast({ variant = "info", message, onClose, dismissible = true }) {
  const icon = {
    success: "✓",
    error: "✕",
    warning: "⚠",
    info: "ℹ"
  }[variant] || "ℹ";

  return (
    <div className={`toast ${variant}`} role="alert">
      <span className="toast-icon" aria-hidden="true">{icon}</span>
      <span className="toast-message">{message}</span>
      {dismissible && (
        <button className="toast-close" aria-label="Dismiss notification" onClick={onClose}>
          ✕
        </button>
      )}
      <div className="toast-progress" />
    </div>
  );
}
